services:
  mqtt_broker:
    image: eclipse-mosquitto:latest
    configs:
      - source: mqtt_broker_config
        target: /mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883" # MQTT port
    networks:
      - mqtt_network

  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: tema3
      INFLUXDB_HTTP_AUTH_ENABLED: "false"
      INFLUXDB_RETENTION_POLICY: "autogen"
      INFLUXDB_RETENTION_DURATION: "INF"  # Infinite retention duration
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
    networks:
      - mqtt_network

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSCD2024
    volumes:
      - grafana-data:/var/lib/grafana
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - ./datasources:/etc/grafana/provisioning/datasources
    ports:
      - "3000:3000"
    networks:
      - mqtt_network
    depends_on:
      - influxdb

  adapter:
    image: adapter_image
    networks:
      - mqtt_network
    depends_on:
      - mqtt_broker
      - influxdb
    env_file:
      - .env
    environment:
    - PYTHONUNBUFFERED=1  # Disable output buffering
    depends_on:
      - mqtt_broker
      - influxdb
    command: sh -c "sleep 10 && python adapter.py"

  mqtt_publisher:
    image: eclipse-mosquitto:latest
    command: >
      sh -c "
        mosquitto_pub -h mqtt_broker -p 1883 -t 'UPB/DOCKER' -m '{\"BAT\": 16, \"HUMID\": 36, \"PRJ\": \"SCD\", \"TMP\": 305.3, \"STATUS\": \"OK\"}' && 
        echo 'Message published successfully!' &&
        tail -f /dev/null"
    networks:
      - mqtt_network
    depends_on:
      - mqtt_broker
      - adapter


networks:
  mqtt_network:
    driver: overlay
    # name: mqtt_network

volumes:
  influxdb_data:
    driver: local
  grafana-data:
    driver: local

configs:
  mqtt_broker_config:
    file: ./mosquitto.conf  # Your Mosquitto configuration file path
